### ISSUE TITLE
Create docker containers

### ISSUE THREAD

**Issue by Mubelotix** [Mubelotix/admarus#97]
The container needs to expose access to tcp ports `4002` and `5002`.
It should be made so that port `4001` is accessible from the inside.

I'm not sure whether it should include the webui or not :thinking: 

It would be great if there could also be a second container for the second flavor of the daemon.
Unlike the default daemon that uses no storage and has to index everything when started, the second flavors stores an index on-disk.
The storage-using daemon can be obtained by compiling with the `database-lmdb` feature.
The corresponding container should have a persistent volume to mount to.

**Comment by jphastings** [comment]
It seems that an effective way to handle the stroage-using daemon case would be to _always_ compile/build with the `database-lmdb` code, but turn the feature on or off depending on whether a persistent volume is made available to the container.

I'd implement this in the docker image by:
1. Setting up the Docker image to have a directory at `/data` or similar
2. Have that directory _inside_ the image contain a file like `.admarus-no-stored-index`
3. Set up the launch command for Admarus in the container to be something like `admarusd --store-index=$([[ -f "/data/.admarus-np-stored-index" ]] && "false" || "/data")`

Now, when someone runs the docker image with a volume mapped to `/data`, the `.admarus-no-stored-index` _isn't_ present, and the server will store in the mounted volume. When the image has no mapped volume, the presence of the `.admarus-no-stored-index` turns off that feature.

**Comment by Mubelotix** [comment]
I would agree with you if that was possible. Unfortunately, enabling `database-lmdb` disables the in-memory index. That's due to implementation details. What can be done however is compiling both binaries and shipping them both in the same container. Depending on the presence of a mounted volume, one of them could be called. Would that be convenient?
